default_job = "run"

[jobs.check]
command = ["cargo", "check"]
need_stdout = false

[jobs.run]
command = [
    "cargo", "run", "--bin=zumblezay_server"
]
need_stdout = true
allow_warnings = true
background = false
on_change_strategy = "kill_then_restart"
env.RUST_LOG = "debug,tower_http=debug"
watch = ["src/**/*.rs", "Cargo.toml", "tests/**/*.rs", "src/templates/**/*.html"]

[jobs.test]
command = ["cargo", "test"]
need_stdout = true
watch = ["src/**/*.rs", "Cargo.toml", "tests/**/*.rs", "src/templates/**/*.html"]